-- vim.pack.add({ 'https://github.com/folke/which-key.nvim' })
--
-- vim.defer_fn(function()
--   require('which-key').setup({
--     preset = 'helix',
--     delay = function(ctx)
--       return ctx.plugin and 0 or 400
--     end,
--     win = {
--       wo = {
--         winblend = 3,
--       }
--     },
--   })
--
--   require('which-key').add {
--     { "<leader>b", group = "Buffer" },
--     { "<leader>c", group = "Code" },
--     { "<leader>d", group = "Diff | Debug" },
--     { "<leader>f", group = "File | Find" },
--     { "<leader>g", group = "Git | Commenting" },
--     { "<leader>gg", group = "Github", icon = " " },
--     { "<leader>h", group = "Hunks", icon = " " },
--     { "<leader>k", group = "Kulala", icon = " " },
--     { "<leader>l", group = "Language (LSP)", icon = '󰦨 ' },
--     { "<leader>n", group = "Scratch pads", icon = " " },
--     { "<leader>r", group = "Run tests", icon = '󰙨' },
--     { "<leader>s", group = "Search | Sessions" },
--     { "<tab>", group = "Tabs", icon = "󰓩 " },
--     { "<leader>t", group = "Toggle" },
--     { "<leader>u", group = "Rsync", icon = "󰓦 " },
--     { "<leader>w", group = "Window" },
--     { "<leader>q", group = "Quit" },
--   }
-- end, 200)
